[package]
name = "rustbucket_os"
version = "0.0.1"
authors = ["Adam Gleave <adamg108@hotmail.co.uk>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"
spin = "0.4.5"
volatile = "0.1.0"
